import { Tool, type ToolCategory } from '@/types';

export const toolsRegistry: Tool[] = [
  // Calculators
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    slug: 'age-calculator',
    description: 'Calculate your exact age in years, months, weeks, days, hours, minutes, and seconds from your birth date.',
    category: 'calculators',
    icon: '🎂',
    keywords: ['age', 'birthday', 'calculator', 'birth date', 'how old'],
    popularity: 95,
  },
  {
    id: 'date-difference',
    name: 'Date Difference Calculator',
    slug: 'date-difference-calculator',
    description: 'Calculate the difference between two dates in days, weeks, months, and years.',
    category: 'calculators',
    icon: '📅',
    keywords: ['date', 'difference', 'days between', 'calculator'],
    popularity: 88,
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    slug: 'percentage-calculator',
    description: 'Calculate percentages, percentage increase/decrease, and solve percentage problems easily.',
    category: 'calculators',
    icon: '📊',
    keywords: ['percentage', 'percent', 'calculator', 'math'],
    popularity: 92,
  },
  {
    id: 'emi-calculator',
    name: 'EMI/Loan Calculator',
    slug: 'emi-loan-calculator',
    description: 'Calculate your Equated Monthly Installment (EMI) for home loans, car loans, and personal loans.',
    category: 'finance',
    icon: '💰',
    keywords: ['emi', 'loan', 'calculator', 'interest', 'mortgage'],
    popularity: 90,
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    slug: 'bmi-calculator',
    description: 'Calculate your Body Mass Index (BMI) and understand your health status.',
    category: 'health',
    icon: '⚖️',
    keywords: ['bmi', 'body mass index', 'health', 'weight', 'calculator'],
    popularity: 94,
  },
  {
    id: 'calorie-calculator',
    name: 'Calorie Calculator',
    slug: 'calorie-calculator',
    description: 'Calculate your daily calorie needs based on your age, weight, height, and activity level.',
    category: 'health',
    icon: '🔥',
    keywords: ['calories', 'tdee', 'bmr', 'health', 'diet'],
    popularity: 89,
  },
  {
    id: 'mortgage-calculator',
    name: 'Mortgage Calculator',
    slug: 'mortgage-calculator',
    description: 'Calculate monthly mortgage payments with taxes, insurance, and PMI.',
    category: 'finance',
    icon: '🏠',
    keywords: ['mortgage', 'home loan', 'calculator', 'payment'],
    popularity: 91,
  },
  {
    id: 'tax-calculator',
    name: 'Tax Calculator',
    slug: 'tax-calculator',
    description: 'Estimate your income tax liability based on filing status and income.',
    category: 'finance',
    icon: '📋',
    keywords: ['tax', 'income tax', 'calculator', 'irs'],
    popularity: 87,
  },
  {
    id: 'tip-calculator',
    name: 'Tip Calculator',
    slug: 'tip-calculator',
    description: 'Calculate tips and split bills among multiple people easily.',
    category: 'finance',
    icon: '💵',
    keywords: ['tip', 'gratuity', 'bill split', 'calculator'],
    popularity: 85,
  },
  {
    id: 'fuel-cost-calculator',
    name: 'Fuel Cost Calculator',
    slug: 'fuel-cost-calculator',
    description: 'Calculate the fuel cost for your trip based on distance, fuel efficiency, and gas price.',
    category: 'finance',
    icon: '⛽',
    keywords: ['fuel', 'gas', 'cost', 'trip', 'calculator'],
    popularity: 82,
  },
  // Converters
  {
    id: 'time-zone-converter',
    name: 'Time Zone Converter',
    slug: 'time-zone-converter',
    description: 'Convert time between different time zones around the world.',
    category: 'converters',
    icon: '🌍',
    keywords: ['timezone', 'time', 'converter', 'world clock'],
    popularity: 93,
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    slug: 'unit-converter',
    description: 'Convert between different units of measurement including length, weight, temperature, and more.',
    category: 'converters',
    icon: '🔄',
    keywords: ['unit', 'conversion', 'metric', 'imperial', 'converter'],
    popularity: 90,
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    slug: 'currency-converter',
    description: 'Convert between world currencies with real-time exchange rates.',
    category: 'converters',
    icon: '💱',
    keywords: ['currency', 'exchange rate', 'forex', 'converter'],
    popularity: 96,
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    slug: 'color-converter',
    description: 'Convert colors between HEX, RGB, HSL, and CMYK formats.',
    category: 'converters',
    icon: '🎨',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'converter'],
    popularity: 84,
  },
  {
    id: 'base64-converter',
    name: 'Base64 Encode/Decode',
    slug: 'base64-encode-decode',
    description: 'Encode and decode text to/from Base64 format.',
    category: 'developer',
    icon: '🔐',
    keywords: ['base64', 'encode', 'decode', 'converter'],
    popularity: 86,
  },
  {
    id: 'url-converter',
    name: 'URL Encoder/Decoder',
    slug: 'url-encoder-decoder',
    description: 'Encode and decode URLs for safe transmission over the internet.',
    category: 'developer',
    icon: '🔗',
    keywords: ['url', 'encode', 'decode', 'percent encoding'],
    popularity: 83,
  },
  // Generators
  {
    id: 'password-generator',
    name: 'Password Generator',
    slug: 'password-generator',
    description: 'Generate strong, secure passwords with customizable options.',
    category: 'generators',
    icon: '🔑',
    keywords: ['password', 'generator', 'secure', 'random'],
    popularity: 97,
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    slug: 'qr-code-generator',
    description: 'Generate QR codes for URLs, text, contact info, and more.',
    category: 'generators',
    icon: '📱',
    keywords: ['qr code', 'generator', 'barcode', 'scanner'],
    popularity: 95,
  },
  {
    id: 'qr-code-scanner',
    name: 'QR Code Scanner',
    slug: 'qr-code-scanner',
    description: 'Scan QR codes using your device camera or upload an image.',
    category: 'generators',
    icon: '📷',
    keywords: ['qr code', 'scanner', 'reader', 'camera'],
    popularity: 91,
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    slug: 'barcode-generator',
    description: 'Generate barcodes in various formats including Code128, EAN, and UPC.',
    category: 'generators',
    icon: '📊',
    keywords: ['barcode', 'generator', 'code128', 'ean', 'upc'],
    popularity: 79,
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    slug: 'uuid-generator',
    description: 'Generate universally unique identifiers (UUIDs) in various versions.',
    category: 'generators',
    icon: '🆔',
    keywords: ['uuid', 'guid', 'generator', 'unique id'],
    popularity: 88,
  },
  {
    id: 'random-number-generator',
    name: 'Random Number Generator',
    slug: 'random-number-generator',
    description: 'Generate random numbers within a specified range.',
    category: 'generators',
    icon: '🎲',
    keywords: ['random', 'number', 'generator', 'dice'],
    popularity: 87,
  },
  {
    id: 'random-name-picker',
    name: 'Random Name Picker',
    slug: 'random-name-picker',
    description: 'Randomly select names from a list for contests, giveaways, or decisions.',
    category: 'generators',
    icon: '🎯',
    keywords: ['random', 'name', 'picker', 'selector', 'winner'],
    popularity: 81,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    slug: 'hash-generator',
    description: 'Generate cryptographic hashes (MD5, SHA-1, SHA-256, SHA-512) for any text.',
    category: 'developer',
    icon: '🔏',
    keywords: ['hash', 'md5', 'sha', 'generator', 'cryptographic'],
    popularity: 85,
  },
  // Text Tools
  {
    id: 'text-counter',
    name: 'Text Counter',
    slug: 'text-counter',
    description: 'Count characters, words, sentences, and paragraphs in your text.',
    category: 'text-tools',
    icon: '📝',
    keywords: ['text', 'counter', 'characters', 'words'],
    popularity: 89,
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    slug: 'word-counter',
    description: 'Count words and analyze text statistics in real-time.',
    category: 'text-tools',
    icon: '📄',
    keywords: ['word', 'counter', 'text', 'statistics'],
    popularity: 90,
  },
  {
    id: 'character-counter',
    name: 'Character Counter',
    slug: 'character-counter',
    description: 'Count characters with and without spaces for social media and more.',
    category: 'text-tools',
    icon: '🔤',
    keywords: ['character', 'counter', 'twitter', 'social media'],
    popularity: 88,
  },
  {
    id: 'reading-time-calculator',
    name: 'Reading Time Calculator',
    slug: 'reading-time-calculator',
    description: 'Estimate how long it takes to read a piece of text.',
    category: 'text-tools',
    icon: '⏱️',
    keywords: ['reading', 'time', 'calculator', 'wpm'],
    popularity: 82,
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    slug: 'case-converter',
    description: 'Convert text between uppercase, lowercase, title case, and more.',
    category: 'text-tools',
    icon: '🔠',
    keywords: ['case', 'converter', 'uppercase', 'lowercase', 'title'],
    popularity: 86,
  },
  {
    id: 'remove-duplicates',
    name: 'Remove Duplicate Lines',
    slug: 'remove-duplicate-lines',
    description: 'Remove duplicate lines from text while preserving order.',
    category: 'text-tools',
    icon: '🗑️',
    keywords: ['duplicate', 'remove', 'lines', 'text', 'clean'],
    popularity: 84,
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    slug: 'json-formatter',
    description: 'Format, validate, and beautify JSON data.',
    category: 'developer',
    icon: '📋',
    keywords: ['json', 'formatter', 'beautify', 'validator'],
    popularity: 93,
  },
  // Image Tools
  {
    id: 'password-strength',
    name: 'Password Strength Checker',
    slug: 'password-strength-checker',
    description: 'Check the strength of your password and get improvement suggestions.',
    category: 'generators',
    icon: '🛡️',
    keywords: ['password', 'strength', 'checker', 'security'],
    popularity: 92,
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    slug: 'image-compressor',
    description: 'Compress images to reduce file size while maintaining quality.',
    category: 'image-tools',
    icon: '🖼️',
    keywords: ['image', 'compress', 'optimize', 'resize'],
    popularity: 90,
  },
  {
    id: 'image-resizer',
    name: 'Image Resize Tool',
    slug: 'image-resize-tool',
    description: 'Resize images to specific dimensions while maintaining aspect ratio.',
    category: 'image-tools',
    icon: '📐',
    keywords: ['image', 'resize', 'dimensions', 'scale'],
    popularity: 88,
  },
  {
    id: 'image-format-converter',
    name: 'Image Format Converter',
    slug: 'image-format-converter',
    description: 'Convert images between PNG, JPG, WEBP, and other formats.',
    category: 'image-tools',
    icon: '🔄',
    keywords: ['image', 'format', 'converter', 'png', 'jpg'],
    popularity: 87,
  },
  // PDF Tools
  {
    id: 'pdf-merge',
    name: 'PDF Merge',
    slug: 'pdf-merge',
    description: 'Merge multiple PDF files into a single document.',
    category: 'pdf-tools',
    icon: '📎',
    keywords: ['pdf', 'merge', 'combine', 'join'],
    popularity: 91,
  },
  {
    id: 'pdf-split',
    name: 'PDF Split',
    slug: 'pdf-split',
    description: 'Split PDF files into multiple documents by page range.',
    category: 'pdf-tools',
    icon: '✂️',
    keywords: ['pdf', 'split', 'separate', 'extract'],
    popularity: 85,
  },
  {
    id: 'pdf-compress',
    name: 'PDF Compress',
    slug: 'pdf-compress',
    description: 'Compress PDF files to reduce file size.',
    category: 'pdf-tools',
    icon: '📦',
    keywords: ['pdf', 'compress', 'optimize', 'reduce size'],
    popularity: 89,
  },
  {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    slug: 'pdf-to-image',
    description: 'Convert PDF pages to image files (PNG, JPG).',
    category: 'pdf-tools',
    icon: '🖼️',
    keywords: ['pdf', 'image', 'converter', 'png', 'jpg'],
    popularity: 86,
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    slug: 'image-to-pdf',
    description: 'Convert images to PDF documents.',
    category: 'pdf-tools',
    icon: '📄',
    keywords: ['image', 'pdf', 'converter', 'create'],
    popularity: 88,
  },
];

export const categories: { id: ToolCategory; name: string; description: string; icon: string }[] = [
  { id: 'calculators', name: 'Calculators', description: 'Various calculation tools for everyday needs', icon: '🧮' },
  { id: 'converters', name: 'Converters', description: 'Convert between different units and formats', icon: '🔄' },
  { id: 'generators', name: 'Generators', description: 'Generate passwords, QR codes, and more', icon: '✨' },
  { id: 'text-tools', name: 'Text Tools', description: 'Analyze and manipulate text content', icon: '📝' },
  { id: 'image-tools', name: 'Image Tools', description: 'Compress, resize, and convert images', icon: '🖼️' },
  { id: 'pdf-tools', name: 'PDF Tools', description: 'Merge, split, and convert PDF files', icon: '📄' },
  { id: 'finance', name: 'Finance', description: 'Financial calculators and tools', icon: '💰' },
  { id: 'health', name: 'Health', description: 'Health and fitness calculators', icon: '❤️' },
  { id: 'developer', name: 'Developer', description: 'Tools for developers and programmers', icon: '💻' },
];

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return toolsRegistry.filter((tool) => tool.category === category);
}

export function getToolBySlug(slug: string): Tool | undefined {
  return toolsRegistry.find((tool) => tool.slug === slug);
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase();
  return toolsRegistry.filter(
    (tool) =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.keywords.some((keyword) => keyword.toLowerCase().includes(lowerQuery))
  );
}

export function getPopularTools(limit: number = 10): Tool[] {
  return [...toolsRegistry].sort((a, b) => b.popularity - a.popularity).slice(0, limit);
}
